### ISSUE TITLE
Details:  Failed to download from one or more repositories  1) https://battlescribedata.appspot.com/repos/horus-heresy/index.bsi 

### ISSUE THREAD

**Issue by Zuul-DG** [BSData/horus-heresy#1123]
Details:

Failed to download from one or more repositories

1) https://battlescribedata.appspot.com/repos/horus-heresy/index.bsi
	at net.battlescribe.desktop.a.b$5.a(BattleScribe:394)
	at net.battlescribe.desktop.a.b$5.doInBackground(BattleScribe:356)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zopha** [comment]
They sometimes do disappear for a while but they will come back. It's not our site, we're just the volunteers who update the files, so we don't have control over it.

If you're still getting the error or the data files don't update to at least 9.0.6 then you may have to remove the data source you have and re-add it again. I have done a test update/add and have been able to update on android and windows.

**Comment by capitaladot** [comment]
@Jonskichov horus-heresy is again off of appspot.

**Comment by zopha** [comment]
@Zuul-DG  The heresy entry has been back for awhile now, have you managed to update your datafiles?
