### ISSUE TITLE
Talons of the Emperor contains invalid links

### ISSUE THREAD

**Issue by MWGNZ** [BSData/horus-heresy#727]
Using v56 of the repo (and v6 of talons of the emperor), when trying to create a new Age of Darkness list I get the following error.

I have deleted all data files and re-downloaded them and still get the error.

Details:

There were some problems with your data files. If you continue, this may lead to crashes or other strange behaviour.

1) Talons of the Emperor:a30a-7522-3343-553a:net.battlescribe.model.data.Catalogue@9537e0: The catalogue data file is invalid:

2) New InfoLink:10a1-cf34-987d-60aa:net.battlescribe.model.data.InfoLink@1d8722f: Link must have a target that exists

3) New InfoLink:b241-f0d3-2997-a14e:net.battlescribe.model.data.InfoLink@875d72: Link must have a target that exists

4) New InfoLink:7f40-2a9b-838c-84e8:net.battlescribe.model.data.InfoLink@941f96: Link must have a target that exists

5) New InfoLink:340e-98dc-db85-94a2:net.battlescribe.model.data.InfoLink@16a8680: Link must have a target that exists
	at net.battlescribe.desktop.rostereditor.RosterEditorFrame.a(BattleScribe:716)
	at net.battlescribe.desktop.rostereditor.RosterEditorFrame.a(BattleScribe:586)
	at net.battlescribe.desktop.rostereditor.f.i(BattleScribe:314)
	at net.battlescribe.desktop.rostereditor.f.b(BattleScribe:478)
	at net.battlescribe.desktop.rostereditor.f.b(BattleScribe:37)
	at net.battlescribe.desktop.rostereditor.f$3.actionPerformed(BattleScribe:375)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at java.awt.Dialog.setVisible(Unknown Source)
	at net.battlescribe.desktop.rostereditor.RosterEditorFrame.W(BattleScribe:1728)
	at net.battlescribe.desktop.rostereditor.RosterEditorFrame.f(BattleScribe:3144)
	at net.battlescribe.desktop.rostereditor.RosterEditorFrame.i(BattleScribe:76)
	at net.battlescribe.desktop.rostereditor.RosterEditorFrame$9.actionPerformed(BattleScribe:2412)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by alphalas** [comment]
I'll take a look at it – the cat is a work in progress though, however, so certain things are not functional yet.

**Comment by MWGNZ** [comment]
Yeah, I've been tracking the dev of it for a bit now and knew it was still pretty alpha. Will log any other bugs that I find as things go on.

**Comment by alphalas** [comment]
lol fairly alpha is putting it nicely lol. Appreciate it though

**Comment by zopha** [comment]
A new file, v50, has been tagged in a release and should be available from appspot in the next few hours.

**Comment by zopha** [comment]
Just had a quick look and battlescribe is pulling in v52 from appspot now and it's loading on my phone.7

It's a WIP but the validation/file load errors are fixed now.
